server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/HireApp
    username: root
    password: root
#  config:
#    import: optional:configserver:http://localhost:8888

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
